### ISSUE TITLE
Only supported by .NET 4.7.1?

### ISSUE THREAD

**Issue by raskolnikoov** [joseftw/JOS.Epi.ContentApi#1]
Is this only supported by .NET 4.7.1? When installed into a .NET 4.6.2 project the JOS.Epi.ContentApi dll is not added to references in the project.

**Comment by joseftw** [comment]
Yeah, that's kinda bad, I will fix it when I have time and target 4.6.1 instead, probably later today, will let you know!

**Comment by joseftw** [comment]
Version 2.0.0 has now been pushed to the nuget feed.
